name: test_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-11.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.4.2
  flutter_icons_null_safety: ^1.1.0
  provider: ^6.0.1
  draggable_widget: ^2.0.0
  reorderables: ^0.6.0
  fl_chart: ^0.41.0
  intl: ^0.17.0
  animated_text_kit: ^4.2.1
  flutter_svg: ^1.1.6 
  timeline_list: ^0.0.6
  timeline_tile: ^2.0.0
  printing: ^5.10.4
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  
flutter:
  uses-material-design: true
  assets:
   - assets/images/side-menu-bg.jpg
   - assets/images/bg.jpg
   - assets/images/logo.png
   - assets/images/default-user.svg
   - assets/images/cow-icon.svg
   - assets/images/fetus-icon.svg
   - assets/images/milk-icon.svg
   - assets/font/RobotoSlabt.ttf